# Generated by Django 5.1.6 on 2025-02-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0009_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetail',
            old_name='delivery_time',
            new_name='delivery_time_in_days',
        ),
    ]
