# Generated by Django 5.1.6 on 2025-02-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0012_auto_20250227_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
